### ISSUE TITLE
Missing `base >= 4.4` constraint in streaming-commons

### ISSUE THREAD

**Issue by hvr** [fpco/streaming-commons#14]
Not a single relased version of `streaming-commons` works with base-4.3, so its .cabal file ought to tell that... (on the bright side, *all* released versions of `streaming-commons` compile fine for all released base versions `>= 4.4`)

**Comment by snoyberg** [comment]
Thanks @hvr, added.

**Comment by hvr** [comment]
@snoyberg now somebody (I can take care if you want) just needs to edit `base >= 4.4` constraints into all older `streaming-commons` releases... :)

**Comment by snoyberg** [comment]
No objection, but I'm curious... who is that really going to help? I've never considered version bounds on base as being particularly useful in situations like this. It makes sense if some old version worked for an old version of GHC, but otherwise just seems to move the error message earlier in the process.

**Comment by hvr** [comment]
It can allow `cabal install foo` to find an alternative install-plan (which doesn't require `streaming-commons`) that doesn't run into a compile-time error. I've seen that with happen with at least one other package.

**Comment by snoyberg** [comment]
I hadn't thought of that case, makes sense. If you're up for making those modifications, I'd appreciate it. To be fair, since the latest Hackage fiasco, I'm avoiding editing cabal files on Hackage at all. What's your Hackage username? I'll make you a contributor.

**Comment by hvr** [comment]
@snoyberg I've actually got Hackage trustee-editing privileges (and by now quite a bit of experience editing cabal files)... so you don't need to add me as as maintainer :-)

**Comment by snoyberg** [comment]
OK, good to know we're in good hands ;).

**Comment by hvr** [comment]
@snoyberg done: https://ghc.haskell.org/~hvr/buildreports/streaming-commons.html

**Comment by snoyberg** [comment]
Thanks!
