### ISSUE TITLE
Build failure on master with GHC 7.6.3

### ISSUE THREAD

**Issue by edom** [fpco/streaming-commons#19]
It seems that Cabal wrongly takes bytestring 0.10.0.2 despite streaming-commons.cabal having specified bytestrings >= 0.10.2.0.

```
Data/Streaming/ByteString/Builder.hs:57:8:
    Could not find module `Data.ByteString.Builder.Extra'
    Perhaps you meant
      Data.ByteString.Lazy.Builder.Extras (from bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.
Failed to install streaming-commons-0.1.10.0
```

(while building 'idris')

**Comment by edom** [comment]
Sorry, never mind. It's caused by a conflict with other packages that depend on older versions of bytestring.

**Comment by snoyberg** [comment]
Sorry, only noticing this issue now. Is this still causing you trouble?

**Comment by edom** [comment]
No, it no longer bothers me; I gave up on Idris a long time ago... (not because of this issue though; Idris was just too much hassle for me at that time)

**Comment by snoyberg** [comment]
Thanks for confirming.
