### ISSUE TITLE
fails to build on Windows XP; Share.h not found

### ISSUE THREAD

**Issue by joeyh** [fpco/streaming-commons#21]
0.1.11 fails to build:

Win32File.hsc:34:19: fatal error: Share.h: No such file or directory

I can't find any Share.h or share.h anywhere in the windows filesystem.

I had previously installed 0.1.4.1 w/o this problem. 

I have not checked if this affects later versions of Windows.

**Comment by snoyberg** [comment]
There have been no changes to Win32File.hsc... actually, [ever](https://github.com/fpco/streaming-commons/commits/master/System/Win32File.hsc). I'm pretty confident I've built this code on Windows XP, but I know for a fact that I'm currently able to build it on Windows 8. share.h should be shipping with mingw. For example, on my system:

C:\Program Files (x86)\MinGHC-7.8.4\ghc-7.8.4\mingw\include\share.h

I think this may be an issue with your installation.

**Comment by joeyh** [comment]
Michael Snoyman wrote:
> There have been no changes to Win32File.hsc... actually, ever. I'm pretty
> confident I've built this code on Windows XP, but I know for a fact that I'm
> currently able to build it on Windows 8. share.h should be shipping with mingw.
> For example, on my system:
> 
> C:\Program Files (x86)\MinGHC-7.8.4\ghc-7.8.4\mingw\include\share.h
> 
> I think this may be an issue with your installation.

Seems that the problem was trying to build it in a cygwin terminal,
which used cygwin's gcc, which failed to find that file.

Sorry for the noise.

-- 
see shy jo

**Comment by snoyberg** [comment]
No problem, it's not the first time I've gotten a bug report because of cygwin ;)

**Comment by MagicRB** [comment]
I ran into this when trying to cross compile from Linux to Windows via mingw-w64, looks like mingw-w64 does include that file just differently cased https://github.com/jonasstrandstedt/MinGW/blob/master/MinGW/include/share.h and since im on a case sensitive filesystem it doesnt find it? or rather `hsc2hs` doesnt:
```
Win32File.hsc:34:10: fatal error: Share.h: No such file or directory
```

**Comment by alexfmpe** [comment]
Ran into this as well while cross-compiling with nixpkgs.
Can be reproduced with nix by doing a checkout on https://github.com/alexfmpe/nixpkgs/pull/449004/commits/4232c5227bf930eebc4830193bcc2211a81f4b2b, reverting the last commit and running `nix-build -A pkgsCross.ucrt64.haskell.packages.ghc912.streaming-commons`
