### ISSUE TITLE
Read buffer size in Data.Streaming.Network is hardcoded to 4096

### ISSUE THREAD

**Issue by kdkeyser** [fpco/streaming-commons#22]
I think it would make sense to make the buffer size configurable. I would be happy to look into this and provide a pull request if you think this would be helpful too.

Main use-case is for high-throughput servers: if you need to saturate a 40 Gb/s link, the recvfrom calls to the kernel become a bottleneck when using 4kiB reads. Since these servers often have plenty of memory (64-128 GB is not exception) there is room to increase memory consumption for these buffers if it would result in improved throughput.

FYI, the Go 1.5 runtime uses 32 kiB buffers. I started looking into the performance difference between a very basic data pump benchmark program in Go vs Haskell/Conduit and noticed this to be the cause of the Go test program outperforming the Haskell one when using message sizes larger than 4 kiB (in a simple request/response protocol).

**Comment by snoyberg** [comment]
Let's definitely look into both increasing the default size and making it
configurable. Ideally this can be done without a breaking API change. Let
me know if you have any questions on how to proceed with a PR.
