### ISSUE TITLE
Test failure: FilesystemSpec.hs:40

### ISSUE THREAD

**Issue by phadej** [fpco/streaming-commons#25]
```
Failures:

  test/Data/Streaming/FilesystemSpec.hs:40:
  1) Data.Streaming.Filesystem.Data.Streaming.Filesystem.getFileType other
       uncaught exception: IOException of type PermissionDenied (tmp: createNamedPipe: permission denied (Operation not permitted))
```

It's probably because of my setup (docker container in virtualbox on mac).

**Comment by snoyberg** [comment]
I'll take a PR to fix this, but I can't think of a way to test for that
case correctly, especially since I don't really know what the problem is.

**Comment by phadej** [comment]
There are two options:
- skip the test if `createNamedPipe` fails
  - as it does, if one tries to create a link on docker volume mounted thru many layers to the os x filesystem at the end
- create link on the filesystem the container, e.g. using path generated with `temporary` inside `/tmp`

**Comment by snoyberg** [comment]
I'd be OK with either approach.
