### ISSUE TITLE
bindPortTCP fails to report port in use on OSX

### ISSUE THREAD

**Issue by simonmichael** [fpco/streaming-commons#29]
On OSX, I can run two instances of my yesod app on the same port without error. The first "shadows" the second; the second starts receiving requests after the first terminates (https://github.com/simonmichael/hledger/issues/226). 

I can reproduce this with bindPortTCP:

```haskell
#!/usr/bin/env stack
{- stack runghc --package network --package streaming-commons -}
{-# LANGUAGE OverloadedStrings #-}

import Data.Streaming.Network
import Network.Socket

main = do
  let port = 5001
      host = "*4"
      -- host = "!4"
  putStr "should pass: " >> bindPortTCP port host >>= print
  putStr "should fail: " >> bindPortTCP port host >>= print -- doesn't fail on OSX. With host = "!4" it does
  putStr "should fail: " >> bindPortTCP port host >>= print
```

On GNU/Linux, it fails when expected:
```shell
$ ./226-test.hs
should pass: <socket: 10>
should fail: 226-test.hs: bind: resource busy (Address already in use)
```

but on OSX, it doesn't fail until the third bind:
```shell
$ ./226-test.hs 
should pass: <socket: 22>
should fail: <socket: 23>
should fail: 226-test.hs: bind: resource busy (Address already in use)
```

(I don't know about Windows.)

If I change the host preference from "*4" to "!4", it works as expected.

**Comment by simonmichael** [comment]
(And in wai-handler-launch, "*4" is hard-coded preventing the above workaround).

**Comment by simonmichael** [comment]
I think "*4" here effectively means "any ipv4 or ipv6 hostname of this server where the port has not yet been bound, ipv4 hostname preferred". So, the second bind picks the ipv6 local host, and I can see that second instance of my yesod app by using a url like `http://[0:0:0:0:0:0:0:1]:5001/`.

Is there a way to detect which hostname was selected ? I could display it at startup, reducing confusion. But practically speaking, the right fix for me is probably to specify "127.0.0.1" to select an unambiguous single host.

I'm not sure if there's an issue with streaming-commons here. wai-handler-launch should make this configurable, I think.

**Comment by simonmichael** [comment]
Related: https://github.com/yesodweb/wai/issues/101

**Comment by snoyberg** [comment]
I don't think there's anything we can change in this library. The OS difference in behavior is annoying, but non-trivial to paper over. Would you be interested in sending a PR with a doc fix to make this more explicit?

**Comment by snoyberg** [comment]
Since the original problem has been fixed in wai-handler-launch, closing.
