### ISSUE TITLE
Not exported the data constructors of HostPreference

### ISSUE THREAD

**Issue by yutasth** [fpco/streaming-commons#35]
The function serverSetting in Data.Conduit.Network requires a Data.Streaming.Network.HostPreference as an argument, but thd 
I had to import

**Comment by snoyberg** [comment]
It is intended to use the `IsString` instance, as mentioned in the docs. The constructors are not exposed to allow us to modify the representation in the future.

**Comment by yutasth** [comment]
but the data constructors are not exported in Data.Streaming.Network.
I had to import Data.Streaming.Network.Internal.
Is this intended?

**Comment by snoyberg** [comment]
I'll repeat what I said: you're supposed to use the `IsString` instance, not the constructors directly. The constructors may change in the future. The docs give examples of doing this, e.g. `"*4"` means "all IPv4 addresses."

**Comment by yutasth** [comment]
I import fromString from Data.String and write "serverSetting 80 (fromString "*")" and it works. 
Thanks for your kindness.

**Comment by snoyberg** [comment]
You can just turn on the OverloadedStrings language extension, e.g.:

{-# LANGUAGE OverloadedStrings #-}

**Comment by yutasth** [comment]
I didn't know that extention. Thanks a lot again!
