### ISSUE TITLE
"127.0.0.1" does not work on IPv6-only hosts

### ISSUE THREAD

**Issue by iliastsi** [fpco/streaming-commons#58]
The tests for `yesod-core` and `http-conduit` have started to fail lately on Debian, when the packages are built on IPv6-only hosts.
See [here](https://buildd.debian.org/status/fetch.php?pkg=haskell-yesod-core&arch=i386&ver=1.6.18-1&stamp=1593282031&raw=0) and [here](https://buildd.debian.org/status/fetch.php?pkg=haskell-http-conduit&arch=amd64&ver=2.3.7.3-2&stamp=1595147746&raw=0) for the build logs, as well as [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964400) and [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962913) for the corresponding bug reports.

I believe that the tests are failing because `streaming-common` is using the `AI_ADDRCONFIG` flag on the `getPossibleAddrs` and or the `bindPortGenEx` functions. Could you please consider removing this flag? See also a [discussion](https://github.com/snoyberg/http-client/issues/400) on `http-client` package which had the same problem and removed the above flag.

**Comment by snoyberg** [comment]
Good call
