### ISSUE TITLE
Support base 4.16.0.0 (GHC 9.2.1)

### ISSUE THREAD

**Issue by Jashweii** [fpco/streaming-commons#61]
Streaming-commons doesn't build on base-4.16.0.0 due to changes in Word
In 4.15.0.0 Word8, 16, 32 all boxed Word# while in 4.16.0.0 they box Word8#, Word16# and Word32#

**Comment by ruomad** [comment]
Hello,
There is a patch on headhackage.

**Comment by snoyberg** [comment]
PR welcome

**Comment by ruomad** [comment]
I posted a draft PR with head.hackage patch. It does compile with ghc-9.2.1
