### ISSUE TITLE
Compatibility with text-2.0

### ISSUE THREAD

**Issue by Bodigrim** [fpco/streaming-commons#63]
I've uploaded `text-2.0-rc1` with UTF8 underlying representation. 

Hackage: https://hackage.haskell.org/package/text-2.0/candidate
Changelog: https://hackage.haskell.org/package/text-2.0/candidate/changelog

I'd like to submit a patch for `streaming-commons`, but not sure how to proceed. Seems `streaming-commons` contains cloned bits and pieces from `text-1.1`?..

**Comment by snoyberg** [comment]
A PR will be welcome. I don't know the best way to move ahead with such a PR, I think the relevant code in streaming-commons comes from quite a while ago in text history.
